export const SAVE_INSTORE_CUSTOMERID = 'SAVE_INSTORE_CUSTOMERID';
export const ADD_IN_BASKET = 'ADD_IN_BASKET';
export const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET';

export const LOCATION_REQUEST = 'LOCATION_REQUEST';
export const LOCATION_SUCCESS = 'LOCATION_SUCCESS';
export const LOCATION_FAILURE = 'LOCATION_FAILURE';

export const CHANNELS_PACKAGES_REQUEST = 'CHANNELS_PACKAGES_REQUEST';
export const CHANNELS_PACKAGES_SUCCESS = 'CHANNELS_PACKAGES_SUCCESS';
export const CHANNELS_PACKAGES_FAILURE = 'CHANNELS_PACKAGES_FAILURE';
